require("modules.monitors")
require("modules.autostart")
require("modules.binds")
require("modules.windowrules")
require("modules.input")
require("modules.env")
require("modules.decorations")
require("modules.layout")
require("modules.misc")

